MVTNatalia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('familiares/',include('familiares.urls')),
]

familiares/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index")
]

familiares/models.py
from django.db import models

class Familia(models.Model):
    PARIENTE = (
        (1, "ABUELA"),
        (2, "ABUELO"),
        (3, "MADRE"),
        (4, "PADRE"),
        (5, "HERMANA"),
        (6, "HERMANO"),
        (7, "HIJA/O")
    )
    parentezco = models.PositiveIntegerField("Parentezco", choices=PARIENTE)
    nombre = models.CharField("Nombre",max_length=15)
    apellido = models.CharField("Apellido",max_length=15)
    edad = models.IntegerField("Edad")
    

familiares/views.py
from django.shortcuts import render
from .models import Familia

def index(request):
    familias = Familia.objects.all()
    ctx = {'familias': familias}
    return render(request, "familiares/index.html",ctx)

familiares/templates/familiares/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'familiares/styles.css' %}">
    <title>Familiares</title>
</head>
<body>
    <h1>MVT Natalia Cerda<h1>
    <h3>Familia<h3>
    <table>
        <thead>
            <td>Parentezco</td>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Edad</td>
        <thead>
        {% for familia in familias %}
        <tr>
            <td>{{ familia.get_parentezco_display }}</td>
            <td>{{ familia.nombre }}</td>
            <td>{{ familia.apellido }}</td>
            <td>{{ familia.edad }}</td>
        <tr>
        {% endfor %}
    <table>
</body>
</html>